#!/usr/bin/env zsh

DIR="./zsh-plugins/zsh-autosuggestions/"

if [ -d "$DIR" ]; then
   echo "'$DIR' found ..."
else
    git clone https://github.com/zsh-users/zsh-autosuggestions $DIR
fi

DIR="./zsh-plugins/zsh-syntax-highlighting/"

if [ -d "$DIR" ]; then
   echo "'$DIR' found ..."
else
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $DIR
fi

