#!/usr/bin/env zsh

echo "\n<<< Installing Utility tools: \n exa >>>\n"

if exists exa; then
    echo "exa exists, skipping install"
else
    sudo pacman -S exa
fi

echo "\n<<< Installing Utility tools: \n tldr >>>\n"

if exists tldr; then
    echo "tldr exists, skipping install"
else
    sudo npm i -g tldr
fi

echo "\n<<< Installing Utility tools: \n git-extras >>>\n"

if exists git-extras; then
    echo "git-extras exists, skipping install"
else
    # sudo apt-get install git-extras
fi
