#!/usr/bin/env bash

DOTFILES_PLUGINS=$(cat $DOTFILES_PATH/vscode/extensions)
HOST_PLUGINS=$(code --list-extensions)

NOT_INSTALLED=$(comm -3 <(echo "$DOTFILES_PLUGINS" | sort) <(echo "$HOST_PLUGINS" |sort))

echo "New plugins found:"

while IFS= read -r line; do
    if [[ -n "$line" ]]; then  # Verifica si la variable no está vacía
        echo "... $line ..."
        code --install-extension "$line"
    fi
done <<< "$NOT_INSTALLED"
