global:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]
  - job_name: "cAdvisor"
    static_configs:
      - targets: ["localhost:8080"]