#!/usr/bin/env zsh

echo "\n<<< Installing Utility tools: \n bat >>>\n"

if exists bat; then
    echo "bat exists, skipping install"
else
    sudo apt install bat -y
fi

echo "\n<<< Installing Utility tools: \n exa >>>\n"

if exists exa; then
    echo "exa exists, skipping install"
else
    sudo apt install exa -y
fi

echo "\n<<< Installing Utility tools: \n snap >>>\n"

if exists snap; then
    echo "snap exists, skipping install"
else
    sudo apt-get install snapd -y
fi


echo "\n<<< Installing Utility tools: \n lsd >>>\n"

if exists lsd; then
    echo "lsd exists, skipping install"
else
    sudo snap install lsd
fi


echo "\n<<< Installing Utility tools: \n tldr >>>\n"

if exists tldr; then
    echo "tldr exists, skipping install"
else
    sudo npm i -g tldr
fi

echo "\n<<< Installing Utility tools: \n git-extras >>>\n"

if exists git-extras; then
    echo "git-extras exists, skipping install"
else
    sudo apt-get install git-extras
fi

echo "\n<<< Installing Utility tools: \n wget >>>\n"

if exists wget; then
    echo "wget exists, skipping install"
else
    sudo apt install wget
fi
