#!/usr/bin/env zsh

echo "🔧 Installing Utility tools!"

if exists bat; then
    echo "✨ bat already installed..."
else
    echo "🔧 Installing bat "
    sudo apt install -qq bat -y
    echo "✨ bat already installed..."
fi

if exists snap; then
    echo "✨ snap already installed..."
else
    sudo apt-get install -qq snapd -y
fi

if exists lsd; then
    echo "✨ lsd already installed..."
else
    echo "🔧 Installing lsd"
    sudo snap install lsd
    echo "✨ lsd already installed..."
fi

if exists xclip; then
    echo "✨ xclip already installed..."
else
    echo "🔧 Installing xclip"
    sudo apt install -qq xclip -y
    echo "✨ xclip already installed..."
fi