#!/usr/bin/env zsh

echo "\n<<< Installing fzf >>>\n"

if exists fzf; then
    echo "fzf exists, skipping install"
else
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
fi
