#!/usr/bin/env zsh

if exists fzf; then
    echo "✨ fzf already installed..."
else
  echo "🔧 Installing fzf..."
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf --quiet
  ~/.fzf/install
  echo "✨ fzf already installed..."
fi
