#!/usr/bin/env zsh

if exists starship; then
    echo "✨ starship already installed..."
else
    echo "🔧 Installing starship "
    curl -sS https://starship.rs/install.sh | sh
    eval "$(starship init zsh)"
    echo "✨ starship already installed..."
fi
