#!/usr/bin/env zsh

echo "🔧 Installing Utility tools!"

if exists bat; then
    echo "✨ bat already installed..."
else
    echo "🔧 Installing bat "
    sudo pacman -S bat --noconfirm
    echo "✨ bat already installed..."
fi

if exists lsd; then
    echo "✨ lsd already installed..."
else
    echo "🔧 lsd already installed..."
    sudo pacman -S lsd --noconfirm
    echo "✨ lsd already installed..."
fi