#!/usr/bin/env zsh

echo "🔧 Installing Utility tools!"

if exists bat; then
    echo "✨ bat already installed..."
else
    echo "🔧 Installing bat "
    sudo pacman -S bat --noconfirm
    echo "✨ bat already installed..."
fi

if exists lsd; then
    echo "✨ lsd already installed..."
else
    echo "🔧 Installing lsd"
    sudo pacman -S lsd --noconfirm
    echo "✨ lsd already installed..."
fi

if exists xclip; then
    echo "✨ xclip already installed..."
else
    echo "🔧 Installing xclip"
    sudo pacman -S xclip --noconfirm
    echo "✨ xclip already installed..."
fi