#!/usr/bin/env bash

  directory=$(find $DOTFILES_PATH/scripts/ -mindepth 1 -maxdepth 1  | fzf --preview='bat --color=always {} 2> /dev/null || (echo This is a folder, you can navigate inside it \\n && lsd --tree --classify {})')

  while [[ -d $directory ]] 
  do
    directory=$(find $directory -mindepth 1 -maxdepth 1 | fzf --preview='bat --color=always {} 2> /dev/null || (echo This is a folder, you can navigate inside it \\n && lsd --tree --classify {})')
  done

  "$directory" "$@"